default_index:
    path:     /
    methods:  [GET]
    defaults: { _controller: App:Default:index }

default_random:
    path:     random/{limit}
    methods:  [GET]
    defaults: { _controller: App:Default:random }
    requirements: { limit: '\d+' }
